//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Dropshipping
    {
        public int sno { get; set; }
        public string date { get; set; }
        public string DN { get; set; }
        public string eng_sr { get; set; }
        public Nullable<int> quantity { get; set; }
        public string freight { get; set; }
        public Nullable<bool> checkOK { get; set; }
        public string wono { get; set; }
    }
}
