//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_KQ30
    {
        public int sno { get; set; }
        public string Material { get; set; }
        public string Material_Desc { get; set; }
        public string Specification { get; set; }
        public string Plnt { get; set; }
        public string SLoc { get; set; }
        public string S { get; set; }
        public string SL { get; set; }
        public string Batch { get; set; }
        public string BUn { get; set; }
        public Nullable<int> Unrestricted { get; set; }
        public Nullable<int> Stock_in_Transfer { get; set; }
        public Nullable<int> I_Q_I { get; set; }
        public Nullable<int> Restricted_Use { get; set; }
        public Nullable<int> Blocked { get; set; }
        public Nullable<int> RE { get; set; }
        public string Docu { get; set; }
    }
}
