//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_QC
    {
        public int sno { get; set; }
        public string QCinspect { get; set; }
        public string ship_serialno { get; set; }
        public string product_serialno { get; set; }
        public string error_code { get; set; }
        public string describe { get; set; }
        public string status { get; set; }
        public string issample { get; set; }
        public string ispass { get; set; }
        public string inspect_result { get; set; }
        public string op_user { get; set; }
        public string outsourcing { get; set; }
        public string wono { get; set; }
        public string GUID { get; set; }
        public string error2 { get; set; }
        public string product_date { get; set; }
        public string iclass { get; set; }
    }
}
