//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_StoreHouseStock_Order
    {
        public int sno { get; set; }
        public string OrderGuid { get; set; }
        public string UserId { get; set; }
        public string wono { get; set; }
        public string eng_sr { get; set; }
        public string sales_order { get; set; }
        public string cust_wono { get; set; }
        public Nullable<int> exp_shipquantity { get; set; }
        public Nullable<int> ship_quantity { get; set; }
        public string sap_mark { get; set; }
        public Nullable<int> stock_quantity { get; set; }
        public string sap_in { get; set; }
        public string company_name { get; set; }
        public string address { get; set; }
        public string company_code { get; set; }
        public Nullable<System.DateTime> chk_date { get; set; }
        public string Igroup { get; set; }
        public string del_flag { get; set; }
        public string record { get; set; }
        public Nullable<int> box_quantity { get; set; }
        public string transportation { get; set; }
        public string position { get; set; }
    }
}
