//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreHouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_StoreHouseEntities : DbContext
    {
        public E_StoreHouseEntities()
            : base("name=E_StoreHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<E_Kf10> E_Kf10 { get; set; }
        public virtual DbSet<E_KQ30> E_KQ30 { get; set; }
        public virtual DbSet<E_Weight> E_Weight { get; set; }
        public virtual DbSet<E_ZRSD14P> E_ZRSD14P { get; set; }
        public virtual DbSet<E_ZRSD19> E_ZRSD19 { get; set; }
        public virtual DbSet<Invoicing> Invoicing { get; set; }
        public virtual DbSet<E_Outbound_Details> E_Outbound_Details { get; set; }
        public virtual DbSet<E_Compyany> E_Compyany { get; set; }
        public virtual DbSet<E_StoreHouseStock> E_StoreHouseStock { get; set; }
        public virtual DbSet<E_StoreHouseStock_Order> E_StoreHouseStock_Order { get; set; }
        public virtual DbSet<E_StoreHouseStock_SC> E_StoreHouseStock_SC { get; set; }
        public virtual DbSet<E_StoreHouseStock_In> E_StoreHouseStock_In { get; set; }
        public virtual DbSet<E_ZRSD13> E_ZRSD13 { get; set; }
        public virtual DbSet<E_Package> E_Package { get; set; }
        public virtual DbSet<E_StoreHouseStock_BOS> E_StoreHouseStock_BOS { get; set; }
        public virtual DbSet<E_StoreChartjs> E_StoreChartjs { get; set; }
        public virtual DbSet<E_Dropshipping> E_Dropshipping { get; set; }
        public virtual DbSet<E_Member> E_Member { get; set; }
        public virtual DbSet<E_MemberRole> E_MemberRole { get; set; }
        public virtual DbSet<E_StoreHouse_Role> E_StoreHouse_Role { get; set; }
        public virtual DbSet<E_QC> E_QC { get; set; }
    }
}
