//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Weight
    {
        public int sno { get; set; }
        public string EngSr { get; set; }
        public Nullable<int> Full_Amount { get; set; }
        public Nullable<decimal> Full_GW { get; set; }
        public Nullable<decimal> Full_NW { get; set; }
        public Nullable<int> End_Amount { get; set; }
        public Nullable<decimal> End_GW { get; set; }
        public Nullable<decimal> End_NW { get; set; }
        public string L_W_H { get; set; }
        public string Bettery_Lab { get; set; }
        public string Wono_cust { get; set; }
        public string Item_Cust { get; set; }
        public string Repeat { get; set; }
        public string Mark { get; set; }
        public string Chk { get; set; }
    }
}
