//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_ZRSD14P
    {
        public int sno { get; set; }
        public string wono { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string item { get; set; }
        public string wono_cust { get; set; }
        public string spec_product { get; set; }
        public Nullable<int> order_quantity { get; set; }
        public Nullable<int> shipped_quantity { get; set; }
        public Nullable<int> unshipped_quantity { get; set; }
        public Nullable<int> borrow_count { get; set; }
        public string prod_notes { get; set; }
    }
}
