//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_ZRSD13
    {
        public int sno { get; set; }
        public string gi_date { get; set; }
        public string cust_name { get; set; }
        public string sales_order { get; set; }
        public string order_item { get; set; }
        public string item { get; set; }
        public string spec_desc { get; set; }
        public Nullable<int> quantity { get; set; }
        public string dn_number { get; set; }
        public string dn_item { get; set; }
        public string ship_mark { get; set; }
        public string cust_wono { get; set; }
    }
}
