//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStoreHouse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoicing
    {
        public int sno { get; set; }
        public string wono { get; set; }
        public string wono_cust { get; set; }
        public string avalueDN { get; set; }
        public string engsr { get; set; }
        public Nullable<int> amount { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string mark { get; set; }
        public string i_1 { get; set; }
        public Nullable<int> i_2 { get; set; }
        public string i_3 { get; set; }
        public string i_4 { get; set; }
    }
}
